import type { Metadata } from "next";
import ToursContextProvider from "./context/ToursContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ContextLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <ToursContextProvider>{children}</ToursContextProvider>;
}
